---
run_tasks: true
openfortivpn_packages:
  - openfortivpn
openfortivpn_enable_service: false
openfortivpn_host: ""
openfortivpn_port: 443
openfortivpn_user: ""
openfortivpn_password: ""
openfortivpn_trusted_cert: ""
