---
-
  name: "Ensuring STARTcloud Theme files are present"
  block:
    -
      name: "Creating STARTcloud Directories"
      ansible.builtin.win_file:
        path: "{{ item }}"
        state: directory
      with_items:
        - C:\opt
        - C:\opt\STARTcloud
        - C:\opt\STARTcloud\backgrounds

    -
      name: "Finding Public Desktop Shortcuts"
      ansible.builtin.win_find:
        paths: "C:\\Users\\Public\\Desktop"
        patterns: "*.lnk"
      register: desktop_shortcuts
      ignore_errors: yes

    -
      name: "Removing Public Desktop Shortcuts"
      ansible.builtin.win_file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ desktop_shortcuts.files }}"
      when: desktop_shortcuts.files is defined
      ignore_errors: yes

    -
      name: "Creating Chromium Intial Preferences"
      when: "'chromium' in chocolatey_packages"
      ansible.builtin.win_template:
        src: initial_preferences.json.j2
        dest: C:\Program Files\Chromium\Application\initial_preferences.json
        newline_sequence: '\n'
        backup: true

    -
      name: "Adding Background Image"
      ansible.windows.win_copy:
        src: startcloud-desktop.jpg
        dest: C:\opt\STARTcloud\backgrounds\startcloud-desktop.jpg

    -
      name: "Adding Background Image"
      ansible.windows.win_copy:
        src: startcloud.png
        dest: C:\opt\STARTcloud\backgrounds\startcloud.png

-
  name: "Adjusting Theme Settings"
  block:
    -
      name: "Adjusting Theme Settings AppsUseLightTheme"
      ansible.windows.win_regedit:
        path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize
        name: AppsUseLightTheme
        data: 0
        type: dword

    -
      name: "Adjust Theme Settings SystemUsesLightTheme"
      ansible.windows.win_regedit:
        path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize
        name: SystemUsesLightTheme
        data: 0
        type: dword

    -
      name: "Adjusting Theme Settings TaskbarMn"
      ansible.windows.win_regedit:
        path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: TaskbarMn
        data: 0
        type: dword
        state: present
      ignore_errors: yes

    -
      name: "Adjusting Theme Settings ShowTaskViewButton"
      ansible.windows.win_regedit:
        path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: ShowTaskViewButton
        data: 0
        type: dword
        state: present
      ignore_errors: yes

    -
      name: "Adjusting Theme Settings TaskbarDa"
      ansible.windows.win_regedit:
        path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: TaskbarDa
        data: 0
        type: dword
        state: present
      ignore_errors: yes

    -
      name: "Adjusting Theme Settings TaskbarAl"
      ansible.windows.win_regedit:
        path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: TaskbarAl
        data: 0
        type: dword
        state: present
      ignore_errors: yes

    -
      name: "Adjusting Theme Settings SearchboxTaskbarMode"
      ansible.windows.win_regedit:
        path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Search
        name: SearchboxTaskbarMode
        data: 0
        type: dword
        state: present
      ignore_errors: yes

-
  name: "Adjusting Default User Settings"
  ansible.windows.win_shell: |
    REG LOAD HKLM\Default C:\Users\Default\NTUSER.DAT
    Set-ItemProperty -Path HKLM:\Default\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize -Name AppsUseLightTheme -Value 0 -Type Dword
    Set-ItemProperty -Path HKLM:\Default\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize -Name SystemUsesLightTheme -Value 0 -Type Dword
    Set-itemproperty -Path HKLM:\Default\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced -Name TaskbarMn -Value 0 -Type Dword
    New-itemproperty -Path HKLM:\Default\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced -Name ShowTaskViewButton -Value 0 -PropertyType Dword
    New-itemproperty -Path HKLM:\Default\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced -Name TaskbarDa -Value 0 -PropertyType Dword
    New-itemproperty -Path HKLM:\Default\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced -Name TaskbarAl -Value 0 -PropertyType Dword
    reg delete HKU\default\software\Microsoft\Windows\CurrentVersion\Run /v OneDriveSetup /f 
    REG UNLOAD HKLM\Default
