--- 
- 
  become: true
  name: "Update nginx confs for Docova + PHP"
  template: "src=../templates/default-site.conf dest=/etc/nginx/sites-available/{{ id }} owner=www-data group=www-data mode=0644"
- name: Creating Dev Folder Symfony
  file:
    path: /var/html/www/docova/var/cache/dev/profiler
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data
    recurse: yes
- name: Recursively change ownership of a directory
  file:
    path: /var/html/www/
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
- 
  become: true
  file: "src=/etc/nginx/sites-available/{{ id }} dest=/etc/nginx/sites-enabled/{{ id }} owner=www-data group=www-data state=link"
  name: "Enable site"
  notify: 
    - "restart nginx"
- name: Removing Default Config
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/nginx/sites-available/default
    - /etc/nginx/sites-available/acme.docova.net
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-enabled/acme.docova.net
  notify: 
    - "restart nginx"
