---
#-
#  name: "Creating STARTcloud Administrator User"
#  block:
#    -
#      name: "Lowering password complexity requirements"
#      community.windows.win_security_policy:
#        section: System Access
#        key: PasswordComplexity
#        value: 0
#
#    -
#      name: "Adding Startcloud as admin user"
#      ansible.windows.win_user:
#        name: "{{ service_user | default('STARTcloud') }}"
#        password: "{{ service_user_password | default('STARTcloud24@!') }}"
#        state: present
#        password_never_expires: true
#        groups:
#          - Administrators
#
#    -
#      name: "Restoring original password complexity requirements"
#      community.windows.win_security_policy:
#        section: System Access
#        key: PasswordComplexity
#        value: 1

-
  name: "Setting User Configurations"
  block:
    -
      name: "Setting administrator password never expires"
      ansible.windows.win_user:
        name: administrator
        password_never_expires: true

#    -
#      name: "Setting service user password never expires"
#      ansible.windows.win_user:
#        name: "{{ service_user | default('STARTcloud') }}"
#        password_never_expires: true
