---
- name: "Linux : installing snmp"
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - "{{ snmp_packages }}"
    - "{{ snmp_additional_packages }}"
  tags:
    - packages

- name: "Linux : creating snmp extension directory"
  become: true
  ansible.builtin.file:
    path: "{{ snmp_extension_scripts }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
    seuser: system_u
    serole: object_r
    setype: lib_t
    selevel: s0
  tags:
    - configuration

- name: "Linux : installing snmp extension"
  become: true
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: '{{ snmp_extension_scripts + "/" }}'
    owner: root
    group: root
    mode: "0755"
    seuser: system_u
    serole: object_r
    setype: lib_t
    selevel: s0
  with_items:
    - "{{ snmp_extension_list }}"
  tags:
    - configuration

- name: "Linux : installing snmp extension proxmox"
  become: true
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/librenms/librenms-agent/master/agent-local/proxmox"
    dest: '{{ snmp_extension_scripts + "/" }}'
    owner: root
    group: root
    mode: "0755"
    seuser: system_u
    serole: object_r
    setype: lib_t
    selevel: s0
  when: '"pve" in ansible_kernel'
  tags:
    - configuration

- name: "Linux : configuring snmpd daemon"
  become: true
  ansible.builtin.template:
    src: "default/snmpd.{{ ansible_os_family }}.j2"
    dest: "{{ snmp_daemon_config }}"
    owner: root
    group: root
    mode: "0644"
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  notify:
    - Restart snmp

- name: "Linux : checking snmp config"
  become: true
  ansible.builtin.template:
    src: "snmp/snmpd.conf.j2"
    dest: "{{ snmp_config }}"
    owner: root
    group: root
    mode: "0600"
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  check_mode: true
  notify: Reconfigure snmp
  tags:
    - configuration

- name: "Applying SNMP configuration changes"
  ansible.builtin.meta: flush_handlers
  tags:
    - configuration
