---
- name: "Restarting Telegraf"
  ansible.builtin.service:
    name: telegraf
    state: restarted
    enabled: true
  when: not telegraf_agent_docker
  become: true

- name: "Restarting Telegraf Container"
  community.docker.docker_container:
    name: "{{ telegraf_agent_docker_name }}"
    restart: true
  when: telegraf_agent_docker

- name: "Creating Telegraf install marker"
  ansible.windows.win_file:
    path: "{{ telegraf_win_install_dir }}\\.installed"
    state: touch

- name: "Restarting Windows Telegraf"
  ansible.windows.win_service:
    name: Telegraf
    start_mode: auto
    state: restarted

- name: "Restarting MacOS Telegraf"
  ansible.builtin.command: brew services restart telegraf
  changed_when: true
