---
-
  name: "Enabling Windows Emergency Management Services (EMS) and Serial Console capability"
  ansible.windows.win_shell: |
    DISM /Online /Add-Capability /CapabilityName:Windows.Desktop.EMS-SAC.Tools~~~~0.0.1.0
  register: ems_sac_result
  ignore_errors: true

-
  name: "Enabling Serial Emergency Management Console"
  ansible.windows.win_shell: |
    bcdedit /ems ON
    bcdedit /bootems ON
    bcdedit /emssettings EMSPORT:1 EMSBAUDRATE:115200
  when: ems_sac_result is succeeded or ems_sac_result is failed
