---
galaxy_info:
  role_name: motd
  author: MarkProminic
  description: Packer/Ad-Hoc MOTD configurations
  company: STARTCloud
  issue_tracker_url: https://github.com/STARTcloud/startcloud_roles/issues
  license: license (Apache)
  min_ansible_version: '2.9'
  platforms:
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags: []

dependencies:
  - role: startcloud.startcloud_roles.serial

collections:
  - startcloud.startcloud_roles

allow_duplicates: false
