---
- name: "Disabling transparent huge pages on systemd systems"
  ansible.builtin.include_tasks: disable_transparent_hugepages.yml
  when:
    - mongodb_disable_transparent_hugepages | bool
    - ansible_service_mgr == "systemd"

- name: "Configuring the MongoDB APT repository"
  when: mongodb_package == 'mongodb-org'
  block:
    - name: "Installing the APT repository prerequisites"
      ansible.builtin.apt:
        name:
          - ca-certificates
          - gnupg
        state: present
        update_cache: true

    - name: "Gathering DEB architecture"
      ansible.builtin.command: dpkg --print-architecture
      register: mongodb_deb_architecture
      changed_when: false

    - name: "Creating keyrings directory for repository GPG keys"
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: "Downloading the armored MongoDB signing key"
      ansible.builtin.get_url:
        url: "{{ mongodb_apt_key_url }}"
        dest: "{{ mongodb_apt_key_armored_path }}"
        mode: "0644"

    - name: "Dearmoring the MongoDB signing key"
      ansible.builtin.command:
        cmd: "gpg --batch --dearmor -o {{ mongodb_apt_keyring_path }} {{ mongodb_apt_key_armored_path }}"
        creates: "{{ mongodb_apt_keyring_path }}"

    - name: "Setting permissions on the dearmored MongoDB signing key"
      ansible.builtin.file:
        path: "{{ mongodb_apt_keyring_path }}"
        mode: "0644"

    - name: "Adding the MongoDB APT repository"
      ansible.builtin.apt_repository:
        repo: "{{ mongodb_repository }}"
        filename: "mongodb-org-{{ mongodb_major_version }}"
        state: present
        update_cache: true

- name: "Installing MongoDB package"
  ansible.builtin.apt:
    name: "{{ mongodb_package }}{% if (mongodb_version | length > 3) %}={{ mongodb_version }}{% endif %}"
    state: "{{ mongodb_package_state }}"
    update_cache: true

- name: "Checking if NUMA is available on host"
  ansible.builtin.command: "ls -1 /proc/1/numa_maps"
  register: numa_available
  ignore_errors: true
  changed_when: false
  check_mode: false
  when: mongodb_use_numa | bool

- name: "Not using NUMA if it is unavailable on host"
  ansible.builtin.set_fact:
    mongodb_use_numa: false
  when: (mongodb_use_numa | bool and numa_available.rc != 0)

- name: "Installing numactl package"
  ansible.builtin.apt:
    name: numactl
    state: present
  when: mongodb_use_numa | bool

- name: "Adding systemd configuration if present"
  ansible.builtin.template:
    src: mongodb.service.j2
    dest: "/lib/systemd/system/{{ mongodb_daemon_name }}.service"
    owner: root
    group: root
    mode: "0644"
  when:
    - ansible_service_mgr == "systemd"
    - mongodb_manage_systemd_unit | bool
  notify:
    - Reload systemd

- name: "Adding symlink for systemd"
  ansible.builtin.file:
    src: "/lib/systemd/system/{{ mongodb_daemon_name }}.service"
    dest: "/etc/systemd/system/multi-user.target.wants/{{ mongodb_daemon_name }}.service"
    state: link
  when:
    - ansible_service_mgr == "systemd"
    - mongodb_manage_systemd_unit | bool
  notify:
    - Reload systemd

- name: "Installing PyMongo package"
  ansible.builtin.apt:
    name: "{{ mongodb_pymongo_package }}"
    state: present
  when: not mongodb_pymongo_from_pip | bool

- name: "Installing PIP"
  ansible.builtin.apt:
    pkg: "{{ mongodb_pymongo_deps }}"
    state: present
  when: mongodb_pymongo_from_pip | bool

- name: "Installing setuptools"
  ansible.builtin.apt:
    pkg: "{{ mongodb_python_setuptools }}"
    state: present
  when: mongodb_pymongo_from_pip | bool

- name: "Installing PyMongo from PIP"
  ansible.builtin.pip:
    name: pymongo
    state: "{{ 'present' if mongodb_pymongo_pip_version else 'latest' }}"
    version: "{{ mongodb_pymongo_pip_version | default(omit, true) }}"
    executable: "{{ mongodb_pip_executable }}"
  when: mongodb_pymongo_from_pip | bool
