galaxy_info:
  role_name: power_management
  author: MarkProminic
  description: Configure Windows power management settings
  company: STARTCloud
  issue_tracker_url: https://github.com/STARTcloud/startcloud_roles/issues
  license: license (Apache)
  min_ansible_version: '2.9'
  platforms:
    - name: Windows
      versions:
        - '10'
        - '11'
        - '2019'
        - '2022'

  galaxy_tags: 
    - windows
    - power
    - hibernate
    - screensaver

dependencies: []

collections:
  - startcloud.startcloud_roles

allow_duplicates: false
