---
- name: "Including OS-specific vars"
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: "Updating yum cache"
  ansible.builtin.dnf:
    update_cache: true

- name: "Upgrading all yum packages"
  ansible.builtin.command: dnf -y upgrade
  register: cockpit_dnf_upgrade
  changed_when: "'Nothing to do' not in cockpit_dnf_upgrade.stdout"

- name: "Installing EPEL repo"
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: "Installing Cockpit"
  ansible.builtin.dnf:
    name: "cockpit"
    state: present
