---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    run_tasks: true
  tasks:
    - name: "Include the conky role"
      ansible.builtin.include_role:
        name: conky
