---
run_tasks: true
count_progress: true
progress_units: 1
progress_role_description: "Configuring BGinfo"

# BGInfo URLs
bginfo_config_url: "https://www.m4kr.net/downloads/Prominic.bgi"
bginfo_shortcut_url: "https://www.m4kr.net/downloads/Bginfo64.lnk"
bginfo_background_v2_url: "https://www.m4kr.net/downloads/ProminicBackgroundv2.bmp"
bginfo_background_jpg_url: "https://www.m4kr.net/downloads/ProminicBackground.jpg"

# BGInfo directories
bginfo_directory: "C:\\opt\\Prominic.NET\\backgrounds"
startup_directory: "C:\\Users\\Administrator\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup"
