---
galaxy_info:
  role_name: nginx
  author: Mark Gilbert
  description: Installs and configures the Nginx web server on Linux, FreeBSD and OpenBSD hosts.
  company: STARTcloud
  issue_tracker_url: https://github.com/STARTcloud/startcloud_roles/issues
  license: Apache-2.0
  min_ansible_version: '2.15'
  platforms:
    - name: Debian
      versions: ['bookworm', 'trixie']
    - name: Ubuntu
      versions: ['jammy', 'noble']
    - name: EL
      versions: ['8', '9']
    - name: ArchLinux
    - name: FreeBSD
      versions: ['14.0']
    - name: OpenBSD
      versions: ['7.3']
    - name: SLES
      versions: ['15SP5']
  galaxy_tags:
    - nginx
    - web
    - webserver
    - proxy
dependencies: []
collections:
  - startcloud.startcloud_roles
