---
- name: "Getting VirtualBox version."
  changed_when: false
  ansible.builtin.command: "cat /home/{{ user }}/.vbox_version"
  register: virtualbox_version

- name: "Mounting VirtualBox guest additions ISO."
  ansible.posix.mount:
    fstype: iso9660
    name: /tmp/vbox
    opts: loop
    src: "/home/{{ user }}/VBoxGuestAdditions_{{ virtualbox_version.stdout }}.iso"
    state: mounted

- name: "Running VirtualBox guest additions installation."
  changed_when: true
  failed_when: false
  ansible.builtin.command: "sh /tmp/vbox/VBoxLinuxAdditions.run"

- name: "Unmounting VirtualBox guest additions ISO."
  ansible.posix.mount:
    fstype: iso9660
    name: /tmp/vbox
    src: "/home/{{ user }}/VBoxGuestAdditions_{{ virtualbox_version.stdout }}.iso"
    state: absent

- name: "Deleting VirtualBox guest additions ISO."
  ansible.builtin.file:
    path: "/home/{{ user }}/VBoxGuestAdditions_{{ virtualbox_version.stdout }}.iso"
    state: absent
