---
- name: "Creating /mnt/hgfs directory for synced folder mounts."
  ansible.builtin.file:
    path: /mnt/hgfs
    state: directory
    mode: "0755"

- name: "Installing open-vm-tools."
  ansible.builtin.apt:
    name: open-vm-tools
    state: present
  when: vmware_install_open_vm_tools

- name: "Installing VMware Tools from the bundled ISO."
  when: "not vmware_install_open_vm_tools"
  block:
    - name: "Creating temporary directories for VMware tools."
      ansible.builtin.file:
        path: "/tmp/{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - vmfusion
        - vmfusion-archive

    - name: "Mounting VMware tools."
      ansible.posix.mount:
        fstype: iso9660
        name: /tmp/vmfusion
        src: "/home/{{ vagrant_user }}/linux.iso"
        state: mounted

    - name: "Finding VMware Tools installer archive."
      ansible.builtin.find:
        paths: /tmp/vmfusion
        patterns: "VMwareTools-*.tar.gz"
      register: vmware_tools_archives

    - name: "Decompressing VMware Tools installer into archive folder."
      ansible.builtin.unarchive:
        src: "{{ (vmware_tools_archives.files | first).path }}"
        dest: /tmp/vmfusion-archive
        remote_src: true

    - name: "Running the VMware tools installer."
      ansible.builtin.command: "/tmp/vmfusion-archive/vmware-tools-distrib/vmware-install.pl --default"
      changed_when: true
      register: vmtools_installer_output

    - name: "Running the VMware tools installer with --force-install."
      ansible.builtin.command: "/tmp/vmfusion-archive/vmware-tools-distrib/vmware-install.pl --default --force-install"
      changed_when: true
      when: "vmtools_installer_output.stdout.find('open-vm-tools') != -1"

    - name: "Unmounting VMware tools."
      ansible.posix.mount:
        fstype: iso9660
        name: /tmp/vmfusion
        src: "/home/{{ vagrant_user }}/linux.iso"
        state: absent

    - name: "Removing temporary directories for VMware tools."
      ansible.builtin.file:
        path: "/tmp/{{ item }}"
        state: absent
      with_items:
        - vmfusion
        - vmfusion-archive

    - name: "Deleting VMWare Tools."
      ansible.builtin.file:
        path: "/home/{{ vagrant_user }}/linux.iso"
        state: absent
