---
run_tasks: true
mattermost_version: "10.5.1"
mattermost_team_name: team
mattermost_domain_name: chat.example.com
mattermost_db_password: "mattermost24@!"
mattermost_user: mattermost
mattermost_group: mattermost
mattermost_db_user: "{{ mattermost_team_name }}_mattermost"
mattermost_db_name: "{{ mattermost_team_name }}_mattermost"
mattermost_root_dir: "/opt/{{ mattermost_team_name }}_mattermost"
mattermost_port: 8065
