motd_org: Prominic.NET
motd_sysadmins_signature: Prominic.NET Support Staff
motd_sysadmins_email: "support@prominic.net"
motd_content: |
  --------------------------------------------------------------------------
                      This system is managed by STARTcloud
  --------------------------------------------------------------------------
             ___                 _      _       _  ____________
            / _ \_______  __ _  (_)__  (_)___  / |/ / __/_  __/
           / ___/ __/ _ \/  ' \/ / _ \/ / __/ /    / _/  / /
          /_/  /_/  \___/_/_/_/_/_//_/_/\__(_)_/|_/___/ /_/
  --------------------------------------------------------------------------
  Support: {{ motd_sysadmins_signature }}
  Email: {{ motd_sysadmins_email }}
  Template Creation Date: {{ ansible_date_time.iso8601 }}
  Template Info: https://vagrant-zones.startcloud.com/changes
  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
