---
motd_org: Prominic.NET
motd_sysadmins_signature: Prominic.NET Support Staff
motd_sysadmins_email: "support@prominic.net"
motd_color_primary: "0;95"
motd_color_secondary: "0;37"
motd_banner_managed_line: >-
  echo -e "${G}┃${R}                 This system is managed by ${G}Prominic.NET${R}                    ${G}┃${R}"
motd_banner_art: |
  echo -e "${G}┃${R}                                                 ${G}PPPPP${R}                     ${G}┃${R}"
  echo -e "${G}┃${R}                                                 ${G}PPPPP${R}                     ${G}┃${R}"
  echo -e "${G}┃${R}                                                  ${G}PPPP${R}                     ${G}┃${R}"
  echo -e "${G}┃${R}                                          ${G}PPP     PPP      PPP${R}             ${G}┃${R}"
  echo -e "${G}┃${R}                                         ${G}PPPPPP    PP   PPPPPPP${R}            ${G}┃${R}"
  echo -e "${G}┃${R}                                         ${G}PPPPPPPPPPPPPPPPPPPPPP${R}            ${G}┃${R}"
  echo -e "${G}┃${R}                     ${G}PPP   PPPPPPP${R}                ${G}PPPP${R}                     ${G}┃${R}"
  echo -e "${G}┃${R}                    ${G}PPPPPPPPPPPPPPPP${R}             ${G}PP PPP${R}                    ${G}┃${R}"
  echo -e "${G}┃${R}                    ${G}PPPPPPPPP   PPPPPP${R}        ${G}PPPP   PPPP${R}                 ${G}┃${R}"
  echo -e "${G}┃${R}                    ${G}PPPPPPP       PPPPPP${R}    ${G}PPPPPP    PPPPP${R}               ${G}┃${R}"
  echo -e "${G}┃${R}                    ${G}PPPPP           PPPP${R}    ${G}PPPPP     PPPPPP${R}              ${G}┃${R}"
  echo -e "${G}┃${R}                    ${G}PPPPP           PPPP${R}     ${G}PPP       PPP${R}                ${G}┃${R}"
  echo -e "${G}┃${R}                    ${G}PPPPP           PPPP${R}                                  ${G}┃${R}"
  echo -e "${G}┃${R}                    ${G}PPPPP           PPPP${R}                                  ${G}┃${R}"
  echo -e "${G}┃${R}                    ${G}PPPPP           PPPP${R}                                  ${G}┃${R}"
  echo -e "${G}┃${R}                    ${G}PPPPPP         PPPPP${R}                                  ${G}┃${R}"
  echo -e "${G}┃${R}                    ${G}PPPPPPPP     PPPPPP${R}                                   ${G}┃${R}"
  echo -e "${G}┃${R}                    ${G}PPPPPPPPPPPPPPPPP${R}                                     ${G}┃${R}"
  echo -e "${G}┃${R}                    ${G}PPPPP PPPPPPPPP${R}                                       ${G}┃${R}"
  echo -e "${G}┃${R}                    ${G}PPPPP${R}                                                 ${G}┃${R}"
  echo -e "${G}┃${R}                    ${G}PPPPP${R}                                                 ${G}┃${R}"
  echo -e "${G}┃${R}                    ${G}PPPPP${R}                       ${W}support at prominic dot net${R}  ${G}┃${R}"
  echo -e "${G}┃${R}                    ${G}PPPPP${R}                                                 ${G}┃${R}"
  echo -e "${G}┃${R}                     ${G}PPP${R}                                                  ${G}┃${R}"
motd_banner_tagline: >-
  echo -e "${G}┃${R}   ${G}:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::${R}   ${G}┃${R}"
motd_content: ""
