---
motd_org: STARTcloud
motd_sysadmins_signature: STARTCloud Contact Email
motd_sysadmins_email: "vagrantup-startcloud@prominic.net"
motd_color_primary: "38;2;106;179;68"
motd_color_secondary: "1;37"
motd_banner_managed_line: >-
  echo -e "${G}┃${R}                  This system is managed by ${G}START${W}cloud${R}                     ${G}┃${R}"
motd_banner_art: |
  echo -e "${G}┃${R}          ${G}______________    ____  ______${W}     __                __${R}          ${G}┃${R}"
  echo -e "${G}┃${R}         ${G}/ ___/_  __/   |  / __ \\/_  __/${W}____/ /___  __  ______/ /${R}          ${G}┃${R}"
  echo -e "${G}┃${R}         ${G}\\__ \\ / / / /| | / /_/ / / / ${W}/ ___/ / __ \\/ / / / __  /${R}           ${G}┃${R}"
  echo -e "${G}┃${R}        ${G}___/ // / / ___ |/ _, _/ / / ${W}/ /__/ / /_/ / /_/ / /_/ /${R}            ${G}┃${R}"
  echo -e "${G}┃${R}       ${G}/____//_/ /_/  |_/_/ |_| /_/ ${W} \\___/_/\\____/\\__,_/\\__,_/${R}             ${G}┃${R}"
motd_banner_tagline: >-
  echo -e "${G}┃${R}                            ${W}OWN YOUR DATA${R}                                  ${G}┃${R}"
