---
-
  name: "Upgrading all apt packages"
  ansible.builtin.apt:
    force_apt_get: true
    upgrade: dist
  when: "ansible_os_family == 'Debian'"

-
  name: "Installing some helpful utilities"
  when: "ansible_os_family == 'Debian'"
  ansible.builtin.apt:
    name:
      - ffmpeg
      - wmctrl
      - xdotool
      - gnome-session
      - gnome-shell-extension-manager
      - gnome-shell-extensions
      - gnome-terminal
      - gnome-tweaks
      - nautilus
      - plymouth
      - plymouth-theme-spinner
      - yaru-theme-icon
      - yaru-theme-unity
      - yaru-theme-sound
      - yaru-theme-gtk
      - yaru-theme-gnome-shell
    state: present
    update_cache: true

-
  name: "Removing bloat"
  when: "ansible_os_family == 'Debian'"
  ansible.builtin.apt:
    name:
      - thunderbird
      - rhythmbox
      - libreoffice*
      - libreoffice-core
      - libreoffice-common
      - libreoffice-draw
      - gnome-2048
      - aisleriot
      - atomix
      - gnome-chess
      - five-or-more
      - hitori
      - iagno
      - gnome-klotski
      - lightsoff
      - gnome-mines
      - gnome-nibbles
      - quadrapassel
      - four-in-a-row
      - gnome-robots
      - gnome-sudoku
      - swell-foop
      - tali
      - gnome-taquin
      - gnome-tetravex
      - gbrainy
      - transmission-gtk
      - byobu
      - cheese
      - totem
      - totem-plugins
      - gnome-power-manager
      - shotwell
    state: absent

-
  name: "Ensuring apt cache is updated"
  ansible.builtin.apt: 
    update_cache: yes
    cache_valid_time: 3600

-
  name: "Setting Graphical Boot Target"
  changed_when: false
  ansible.builtin.command: "systemctl set-default graphical.target"

-
  name: "Creating dconf DB Directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/etc/dconf/db/gdm.d/"
    - "/etc/dconf/db/local.d/"

-
  name: Setting User Dconf
  ansible.builtin.copy:
    content: |
      user-db:user
      system-db:local
    dest: /etc/dconf/profile/user
    mode: "0644"

-
  name: "Setting Global Dconf"
  ansible.builtin.template:
    src: userconf.j2
    dest: /etc/dconf/db/local.d/userconf
    mode: "0644"
    force: yes

-
  name: "Disabling Ubuntu Welcome Screen"
  ansible.builtin.lineinfile: 
    line: "InitialSetupEnable = false"
    path: /etc/gdm3/custom.conf
    regexp: "^[daemon]"
    insertafter: '^[daemon]'

-
  name: "Removing Initial Setup Package"
  ansible.builtin.apt:
    name:
      - gnome-initial-setup
    state: absent
  when: "ansible_os_family == 'Debian'"

-
  name: Updating dconf Configuration for all users
  ansible.builtin.command: dconf update

-
  name: "Disabling Upgrade Prompt"
  ansible.builtin.lineinfile:
    path: /etc/update-manager/release-upgrades
    regexp: '^Prompt='
    line: Prompt=never

-
  name: "Cloning dash-to-panel Gnome Extension"
  ansible.builtin.git:
    repo: https://github.com/home-sweet-gnome/dash-to-panel.git
    dest: /usr/local/src/dash-to-panel

-
  name: "Installing dash-to-panel Gnome Extension Plus for all users"
  ansible.builtin.make:
    chdir: /usr/local/src/dash-to-panel
    target: install
    params:
      DESTDIR: /

-
  name: "Installing Extension -- Sound Output Chooser"
  ansible.builtin.git:
    repo: https://github.com/kgshank/gse-sound-output-device-chooser.git 
    dest:  /usr/share/gnome-shell/extensions/gse-sound-output-device-chooser

-
  name: "Correct Directory Structure for Sound Output Chooser"
  when: "ansible_os_family == 'Debian'"
  changed_when: false
  ansible.builtin.command: "{{ item }}"
  with_items:
    - "cp -r /usr/share/gnome-shell/extensions/gse-sound-output-device-chooser/sound-output-device-chooser@kgshank.net  /usr/share/gnome-shell/extensions"
    - "rm -rf gse-sound-output-device-chooser"

-
  name: "Installing Extension -- Sound Output Chooser"
  ansible.builtin.git:
    repo: https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator.git
    dest: /usr/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com

-
  name: "Enabling Extensions"
  when: "ansible_os_family == 'Debian'"
  changed_when: false
  ansible.builtin.command: "{{ item }}"
  with_items:
    - gnome-extensions enable dash-to-panel@jderose9.github.com
    - gnome-extensions enable sound-output-device-chooser@kgshank.net
    - gnome-extensions enable clipboard-indicator@tudmotu.com

-
  name: "Copying Logout Desktop Shortcut to /usr/share/applications"
  ansible.builtin.template:
    src: Logout.desktop.j2
    dest: /usr/share/applications/Logout.desktop
    mode: "0644"

-
  name: Copy Logout script to /usr/share/applications
  ansible.builtin.template:
    src: logout.sh.j2
    dest: /usr/share/applications/logout.sh
    mode: a+x

-
  name: Copy Logout Desktop Icons to /usr/share/applications
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/share/applications
    mode: "0644"
  with_items:
    - Logout.png

-
  name: "Allowing Access to commonly used functions on Desktop"
  ansible.builtin.template:
    mode: "0644"
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
  with_items:
    -
      src: 47-allow-wifi-scan.pkla.j2
      dest: "/etc/polkit-1/localauthority/50-local.d/47-allow-wifi-scan.pkla"
    -
      src: 45-allow-colord.pkla.j2
      dest: "/etc/polkit-1/localauthority/50-local.d/45-allow-colord.pkla"
    -
      src: universal.pkla.j2
      dest: "/etc/polkit-1/localauthority/50-local.d/universal.pkla"
