---
-
  name: "Reducing Template and Cleaning up System"
  block:
    -
      name: "Clearing last used files and folders"
      ansible.windows.win_shell: |
        Remove-Item "$env:APPDATA\Microsoft\Windows\Recent\AutomaticDestinations\*.automaticDestinations-ms" -FORCE -ErrorAction SilentlyContinue

    -
      name: "Cleaning Temp Files"
      ansible.windows.win_shell: |
        Takeown /d Y /R /f "C:\Windows\Temp\*"
        Icacls "C:\Windows\Temp\*" /GRANT:r administrators:F /T /c /q 2>&1

    -
      name: "Reducing Page File"
      ansible.windows.win_shell: |
        $System = GWMI Win32_ComputerSystem -EnableAllPrivileges
        $System.AutomaticManagedPagefile = $False
        $System.Put()
        $CurrentPageFile = gwmi -query "select * from Win32_PageFileSetting where name='c:\\pagefile.sys'"
        $CurrentPageFile.InitialSize = 512
        $CurrentPageFile.MaximumSize = 512
        $CurrentPageFile.Put()

-
  name: "Verifying Health of Windows Installation"
  when: verify | default(true)
  block:
    -
      name: "Scanning health of the image"
      ansible.windows.win_shell: 'DISM /Online /Cleanup-Image /ScanHealth'

    -
      name: "Starting component cleanup"
      ansible.windows.win_shell: 'DISM /Online /Cleanup-Image /StartComponentCleanup /ResetBase'

    -
      name: "Removing superseded components"
      ansible.windows.win_shell: 'DISM /Online /Cleanup-Image /SPSuperseded'

-
  name: "Preparing for Sysprep"
  when: prepare_sysprep | default(true)
  block:
    -
      name: "Create sysprep.bat"
      ansible.windows.win_copy:
        dest: C:\Windows\Temp\packer\sysprep.bat
        content: |
          C:\Windows\System32\Sysprep\sysprep.exe /generalize /oobe /quiet /shutdown /unattend:C:\Windows\Temp\packer\Autounattend.xml

-
  name: "Cleanup System Wide Proxy (End of Provisioning)"
  when: cleanup_proxy | default(false)
  block:
    -
      name: "Removing System Wide HTTP Proxy"
      ansible.windows.win_environment:
        name: HTTP_PROXY
        state: absent
        level: machine

    -
      name: "Removing System Wide HTTPS Proxy"
      ansible.windows.win_environment:
        name: HTTPS_PROXY
        state: absent
        level: machine

    -
      name: "Resetting WinHTTP Proxy Settings"
      ansible.windows.win_shell: |
        netsh winhttp reset proxy

-
  name: "Removing Appx packages (and their hindering file associations)"
  ansible.windows.win_shell: |
    Get-AppxPackage -name "*OneDriveSync*" | Remove-AppxPackage

-
  name: "Disabling Firewall Profiles"
  ansible.windows.win_shell: |
    Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
