---
dependencies: []

galaxy_info:
  role_name: antivirus
  author: STARTcloud
  description: Antivirus installation and configuration supporting ClamAV and Sophos.
  company: "STARTcloud"
  license: "license (BSD, MIT)"
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
        - focal
        - jammy
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
        - bullseye
    - name: Windows
      versions:
        - "10"
        - "11"
        - "2019"
        - "2022"
  galaxy_tags:
    - networking
    - cloud
    - security
    - antivirus
    - antimalware
    - scan
    - sophos
    - clamav
    - windows
    - linux

collections:
  - startcloud.startcloud_roles
