---
galaxy_info:
  role_name: ipasmartcard_client
  author: Mark Gilbert
  description: Configures an enrolled FreeIPA client for Smart Card authentication.
  company: STARTcloud
  issue_tracker_url: https://github.com/STARTcloud/startcloud_roles/issues
  license: Apache-2.0
  min_ansible_version: '2.15'
  platforms:
    - name: EL
      versions: ['8', '9']
    - name: Fedora
      versions: ['39', '40']
  galaxy_tags:
    - freeipa
    - ipa
    - smartcard
    - identity
    - authentication
dependencies: []
collections:
  - startcloud.startcloud_roles
