---
-
  name: "Ensure that Proxy is Set for APT"
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/proxy.conf
    line: Acquire::http::Proxy "socks5h://{{ proxy[0].user }}:{{ proxy[0].pass }}@{{ proxy[0].host }}:{{ proxy[0].port }}";
