---
- block:
    - ansible.builtin.file:
        path: /etc/update-motd.d/backups
        state: directory
      name: "Create backup folder"
    - name: "Check if we need to move files"
      register: move_output
      ansible.builtin.shell: "ls /etc/update-motd.d/ --ignore=99-footer --ignore=20-update --ignore=backups"
    - args:
        chdir: /etc/update-motd.d/
      name: "Move files to backup folder"
      ansible.builtin.shell: "mv $(ls --ignore=99-footer --ignore=20-update --ignore=backups) /etc/update-motd.d/backups/"
      when: 'move_output.stdout != ""'
  name: "Remove default motd configuration"
  when: remove_default_config
- name: "Restore default motd configuration from backups folder"
  ansible.builtin.shell: "mv /etc/update-motd.d/backups/* /etc/update-motd.d/"
  when: "restore_default_config and not remove_default_config"
- copy:
    dest: /etc/update-motd.d/99-footer
    group: root
    mode: 493
    owner: root
    src: 99-footer
  name: "Add 99-footer file"
  tags:
    - motd
    - common
  when: "add_footer | bool"
- ansible.builtin.file:
    path: /etc/update-motd.d/99-footer
    state: absent
  name: "Delete 99-footer file"
  tags:
    - motd
    - common
  when: "not add_footer | bool"
- name: "Add dynamic message before motd"
  tags:
    - motd
    - common
  ansible.builtin.template:
    dest: /etc/update-motd.d/20-update
    mode: a+x
    src: etc/update-motd.d/20-update.j2
  when: "add_update | bool"
- ansible.builtin.file:
    path: /etc/update-motd.d/20-update
    state: absent
  name: "Remove dynamic message before motd"
  tags:
    - motd
    - common
  when: "not add_update | bool"
- ansible.builtin.file:
    path: /etc/motd
    state: absent
  name: "Delete /etc/motd file"
  tags:
    - motd
    - common
  when: "add_footer | bool"
- name: "Check motd tail supported"
  register: tail_supported
  ansible.builtin.stat:
    path: /etc/update-motd.d/99-footer
  tags:
    - motd
    - common
- name: "Add motd tail"
  tags:
    - motd
    - common
  ansible.builtin.template:
    dest: /etc/motd.tail
    src: etc/motd.j2
  when: "tail_supported.stat.exists | bool"
- name: "Add motd"
  tags:
    - motd
    - common
  ansible.builtin.template:
    dest: /etc/motd
    src: etc/motd.j2
  when: "not tail_supported.stat.exists | bool"
