---
- name: Converge
  hosts: all
  become: true
  vars:
    run_tasks: true
    show_help: true
    settings:
      hostname: startcloud-hostname-test
      domain: example.com
  tasks:
    - name: "Include the hostname role"
      ansible.builtin.include_role:
        name: hostname
