--- 
- 
  apt: 
    update_cache: true
- 
  get_url: 
    dest: /tmp/phpMyAdmin.zip
    url: "https://files.phpmyadmin.net/phpMyAdmin/5.0.3/phpMyAdmin-5.0.3-all-languages.zip"
  name: "Copying phpMyAdmin Zip"
- 
  become: true
  name: "Extract phpMyAdmin"
  unarchive: 
    dest: /tmp
    group: www-data
    owner: www-data
    remote_src: true
    src: /tmp/phpMyAdmin.zip
- 
  become: true
  command: "mv /tmp/phpMyAdmin-5.0.3-all-languages /usr/share/phpmyadmin"
  name: "Move phpMyAdmin install files"
- 
  changed_when: false
  name: "check if nginx is installed"
  register: nginx_conf_dir
  stat: 
    path: /etc/nginx/conf.d
- 
  file: 
    path: /etc/nginx/global.d
    state: directory
  name: "ensure directory for global nginx configuration files exists"
  when: nginx_conf_dir.stat.exists
- 
  name: "ensure phpmyadmin configuration for nginx is installed"
  notify: "restart nginx"
  template: 
    dest: /etc/nginx/global.d/phpmyadmin.conf
    src: nginx.conf.j2
  when: nginx_conf_dir.stat.exists

- 
  set_fact: 
    my_pass: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"
- 
  become: true
  command: "mv /usr/share/phpmyadmin/config.sample.inc.php /usr/share/phpmyadmin/config.inc.php"
  name: "Setting up PHP configuration"
- 
  lineinfile: 
    dest: /usr/share/phpmyadmin/config.inc.php
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  name: "Setting Unique Key"
  with_items: 
    - 
      line: "$cfg['blowfish_secret'] = '{{ my_pass }}';"
      regexp: "$cfg['blowfish_secret'] = '';"
