---
-
  name: "Managing progress for {{ ansible_role_name }}"
  when: count_progress | default(false)
  run_once: true
  block:
    -
      name: "Incrementing global progress step counter for {{ ansible_role_name }}"
      ansible.builtin.set_fact:
        global_current_progress_step: "{{ global_current_progress_step | default(0) | int + 1 }}"

    -
      name: "Including progress reporting task for {{ ansible_role_name }}"
      ansible.builtin.include_role:
        name: startcloud.startcloud_roles.progress
      vars:
        _progress_role_is_setup_run: false
        current_progress_step: "{{ global_current_progress_step | default(0) }}"
        progress_description: "{{ progress_role_description | default('Processing ' + ansible_role_name) }}"

-
  name: "Block to Allow Loading of Variables without running task"
  when: run_tasks
  block:
    - name: "Disabling Windows Security Notification Icon"
      when: disable_security_notifications
      block:
        - name: "Disabling Windows Security Notification Icon"
          ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender Security Center\Systray
            name: HideSystray
            data: 1
            type: dword

        - name: "Disabling Windows Security Notification Icon"
          ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender Security Center\Notifications-Name
            name: DisableNotifications
            data: 1
            type: dword

    - name: "Disabling Windows Feedback Experience program"
      when: disable_feedback
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo
        name: Enabled
        data: 0
        type: dword

    - name: "Stopping Cortana from being used as part of your Windows Search Function"
      when: disable_cortana
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search
        name: AllowCortana
        data: 0
        type: dword

    - name: "Disabling Bing Search in Start Menu"
      when: disable_bing_search
      ansible.windows.win_regedit:
        path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Search
        name: BingSearchEnabled
        data: 0
        type: dword

    - name: "Adding Registry key to prevent bloatware apps from returning"
      when: disable_consumer_features or disable_content_delivery
      block:
        - name: "Ensuring CloudContent registry path exists"
          ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent
            state: present

        - name: "Setting DisableWindowsConsumerFeatures"
          when: disable_consumer_features
          ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent
            name: DisableWindowsConsumerFeatures
            data: 1
            type: dword

        - name: "Ensuring ContentDeliveryManager registry path exists"
          ansible.windows.win_regedit:
            path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
            state: present

        - name: "Setting ContentDeliveryAllowed"
          when: disable_content_delivery
          ansible.windows.win_regedit:
            path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
            name: ContentDeliveryAllowed
            data: 0
            type: dword

        - name: "Setting OemPreInstalledAppsEnabled"
          when: disable_content_delivery
          ansible.windows.win_regedit:
            path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
            name: OemPreInstalledAppsEnabled
            data: 0
            type: dword

        - name: "Setting PreInstalledAppsEnabled"
          when: disable_content_delivery
          ansible.windows.win_regedit:
            path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
            name: PreInstalledAppsEnabled
            data: 0
            type: dword

        - name: "Setting PreInstalledAppsEverEnabled"
          when: disable_content_delivery
          ansible.windows.win_regedit:
            path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
            name: PreInstalledAppsEverEnabled
            data: 0
            type: dword

        - name: "Setting SilentInstalledAppsEnabled"
          when: disable_content_delivery
          ansible.windows.win_regedit:
            path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
            name: SilentInstalledAppsEnabled
            data: 0
            type: dword

    - name: "Turning off Data Collection"
      when: disable_telemetry
      block:
        - name: "Disable Data Collection for HKLM"
          ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection
            name: AllowTelemetry
            data: 0
            type: dword

        - name: "Disabling Data Collection for HKLM (Wow6432Node)"
          ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Policies\DataCollection
            name: AllowTelemetry
            data: 0
            type: dword

        - name: "Disabling Data Collection for HKLM (Windows DataCollection)"
          ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection
            name: AllowTelemetry
            data: 0
            type: dword

    - name: "Disabling Location Tracking"
      when: disable_location_tracking
      block:
        - name: "Ensuring SensorState registry path exists"
          ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Sensor\Overrides\{BFA794E4-F964-4FDB-90F6-51056BFE4B44}
            state: present

        - name: "Setting SensorPermissionState to 0"
          ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Sensor\Overrides\{BFA794E4-F964-4FDB-90F6-51056BFE4B44}
            name: SensorPermissionState
            data: 0
            type: dword

        - name: "Ensuring LocationConfig registry path exists"
          ansible.windows.win_regedit:
            path: HKLM:\SYSTEM\CurrentControlSet\Services\lfsvc\Service\Configuration
            state: present

        - name: "Setting LocationConfig Status to 0"
          ansible.windows.win_regedit:
            path: HKLM:\SYSTEM\CurrentControlSet\Services\lfsvc\Service\Configuration
            name: Status
            data: 0
            type: dword

    - name: "Stopping and disabling Diagnostics Tracking Service"
      when: disable_diagnostics_tracking
      ansible.windows.win_service:
        name: DiagTrack
        state: stopped
        start_mode: disabled

    - name: "Setting Mixed Reality Portal value to 0"
      ansible.windows.win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Holographic
        name: FirstRunSucceeded
        data: 0
        type: dword

    - name: "Disabling live tiles"
      ansible.windows.win_regedit:
        path: HKCU:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\PushNotifications
        name: NoTileApplicationNotification
        data: 1
        type: dword

    - name: "Applying Blackscreen Resolution: Disable Firewall rule on Container log in and out"
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy
        name: DeleteUserAppContainersOnLogoff
        data: 1
        type: dword
