---
-
  name: "Block to Allow Loading of Variables without running task"
  when: run_tasks
  block:
    -
      name: "Installing Telegraf"
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        name:
          - telegraf
    
    -
      name: "Adding Telegraf Configurations"
      when: ansible_os_family == 'Debian'
      ansible.builtin.template:
        mode: '0644'
        dest: "{{ item.dest }}"
        src: "{{ item.src }}"
      with_items:
        -
          src: telegraf.cnf.j2
          dest: "/etc/telegraf/telegraf.conf"
    
    -
      name: "Enabling Telegraf"
      when: ansible_os_family == 'Debian'
      ansible.builtin.service:
        name: telegraf
        state: started
        enabled: true
