---
galaxy_info:
  role_name: ntp
  author: MarkProminic
  description: NTP installation and configuration
  company: STARTCloud
  issue_tracker_url: https://github.com/STARTcloud/startcloud_roles/issues
  license: license (Apache)
  min_ansible_version: '2.9'
  platforms:
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: FreeBSD
      versions:
        - all
    - name: Suse
      versions:
        - all
    - name: Archlinux
      versions:
        - all

  galaxy_tags:
    - system
    - ntp
    - date
    - time
    - timezone
    - chrony
    - chronyd
    - synchronization

dependencies: []

collections:
  - startcloud.startcloud_roles

allow_duplicates: false
