---
- name: "Block to Allow Loading of Variables without running task"
  when: run_tasks
  block:
    - name: "Installing Sendmail Packages"
      ansible.builtin.apt:
        name: "{{ sendmail_packages }}"
        state: present
        update_cache: true
      register: sendmail_package_install
      until: sendmail_package_install is succeeded
      retries: 5
      delay: 5
    - name: "Ensuring the Sendmail configuration group exists"
      ansible.builtin.group:
        name: "{{ sendmail_config_group }}"
        state: present
        system: true
    - name: "Templating Sendmail Configuration"
      ansible.builtin.template:
        src: "sendmail.mc.j2"
        dest: "{{ sendmail_config_dir }}/sendmail.mc"
        owner: root
        group: "{{ sendmail_config_group }}"
        mode: "0644"
      notify:
        - "Rebuilding Sendmail Configuration"
        - "Restarting Sendmail Service"
    - name: "Enabling and Starting Sendmail Service"
      ansible.builtin.systemd_service:
        name: "{{ sendmail_service_name }}"
        state: started
        enabled: true
