---
-
  name: "Restarting keepalived"
  ansible.builtin.service:
    name: keepalived
    state: restarted

-
  name: "Reloading keepalived"
  ansible.builtin.service:
    name: keepalived
    state: reloaded
