---
- name: "Block to Allow Loading of Variables without running task"
  when: run_tasks
  block:
    - name: "Installing Kayak and TFTP"
      community.general.pkg5:
        name:
          - kayak
          - kayak-kernel
          - tftp
          - isc-dhcp

    - name: "Checking if Image Has Been Downloaded"
      register: file_exists
      ansible.builtin.stat:
        path: "/var/kayak/kayak/{{ omnios_source_file }}"
        checksum_algorithm: sha256

    - name: "Downloading PXE Boot Installer Image"
      ansible.builtin.get_url:
        dest: "/var/kayak/kayak/{{ omnios_source_file }}"
        mode: "0644"
        url: "{{ omnios_source_url }}"
      when: not file_exists.stat.exists

    - name: "Enabling and Starting Kayak"
      ansible.builtin.service:
        name: kayak
        state: started

    - name: "Enabling and Starting TFTP"
      ansible.builtin.service:
        name: tftp/udp6
        state: started

    - name: "Converting Mac Address to Extended Format"
      ansible.builtin.set_fact:
        modified_macaddr: "{{ '{}{}:{}{}:{}{}:{}{}:{}{}:{}{}'.format(*pxe_client_mac) }}"

    - name: "Setting DHCP Settings"
      become: true
      ansible.builtin.template:
        dest: "{{ item.dest }}"
        mode: "0755"
        src: "{{ item.src }}"
      with_items:
        - dest: /etc/dhcpd.conf
          src: dhcpd.conf

    - name: "Enabling and Starting DHCP"
      ansible.builtin.service:
        name: "dhcp:ipv4"
        state: started

    - name: "Setting Boot Configurations for Kayak and TFTP"
      become: true
      ansible.builtin.template:
        dest: "{{ item.dest }}"
        mode: "0755"
        src: "{{ item.src }}"
      with_items:
        - dest: /tftpboot/boot/loader.conf.local
          src: loader.conf.local
        - dest: /tftpboot/boot/grub/menu.lst
          src: menu.lst

    - name: "Creating the XML Storage Directory"
      ansible.builtin.file:
        path: /var/kayak/kayak/xml
        state: directory
        mode: "0755"

    - name: "Creating the Promimic Script Directories"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - /opt/promimic
        - /opt/promimic/scripts

    - name: "Setting Up XML2AI"
      become: true
      ansible.builtin.template:
        dest: "{{ item.dest }}"
        mode: a+x
        src: "{{ item.src }}"
      with_items:
        - dest: /opt/promimic/scripts/xml2ai
          src: xml2ai

    - name: "Generating the XML from hosttemplate for {{ pxe_profile }}"
      become: true
      ansible.builtin.template:
        dest: "{{ item.dest }}"
        mode: "0644"
        src: "{{ item.src }}"
      with_items:
        - dest: "/var/kayak/kayak/xml/{{ pxe_client_hostname }}.xml"
          src: "{{ pxe_profile }}hosttemplate.xml"

    - name: "Placing /var/kayak/kayak/xml/machineschema.dtd"
      become: true
      ansible.builtin.template:
        dest: "{{ item.dest }}"
        mode: "0644"
        src: "{{ item.src }}"
      with_items:
        - dest: "/var/kayak/kayak/xml/machineschema.dtd"
          src: "machineschema.dtd"

    - name: "Adding Path to System Profile"
      ansible.builtin.lineinfile:
        mode: "0644"
        path: "/etc/profile"
        line: "PATH=$PATH:"
        insertbefore: EOF
      loop:
        - "PATH=$PATH:{{ profile_path }}"
        - "export PATH"

    - name: "Generating Kayak Configurations with XML2AI for {{ pxe_client_hostname }}"
      become: true
      changed_when: true
      ansible.builtin.shell:
        cmd: "pfexec python3 {{ pxe_script_generator }} < /var/kayak/kayak/xml/{{ pxe_client_hostname }}.xml"
