galaxy_info:
  role_name: exim
  author: Mark Gilbert
  description: Installs and configures the Exim mail transfer agent on Linux.
  company: STARTcloud
  issue_tracker_url: https://github.com/STARTcloud/startcloud_roles/issues
  license: Apache-2.0
  min_ansible_version: '2.15'
  platforms:
    - name: Debian
      versions: ['bookworm', 'trixie']
    - name: Ubuntu
      versions: ['jammy', 'noble']
    - name: EL
      versions: ['8', '9']
  galaxy_tags:
    - mail
    - exim
    - smtp
    - email
dependencies: []
collections:
  - startcloud.startcloud_roles
