---
-
  name: "Disabling Firewall Profiles"
  ansible.windows.win_shell: |
    Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False

-
  name: "Ensuring OpenSSH Server firewall rule exists"
  community.windows.win_firewall_rule:
    name: OpenSSH-Server-In-TCP
    direction: in
    action: allow
    protocol: tcp
    localport: 22
    description: OpenSSH Server (sshd)
    enabled: true
