galaxy_info:
  role_name: nextcloud
  author: Mark Gilbert
  description: Installs and configures a single-node Nextcloud server with nginx, PHP-FPM, and a MariaDB database.
  company: STARTcloud
  issue_tracker_url: https://github.com/STARTcloud/startcloud_roles/issues
  license: Apache-2.0
  min_ansible_version: '2.15'
  platforms:
    - name: Debian
      versions: ['bookworm', 'trixie']
    - name: Ubuntu
      versions: ['jammy', 'noble']
  galaxy_tags:
    - nextcloud
    - cloud
    - storage
    - php
    - nginx
dependencies: []
collections:
  - startcloud.startcloud_roles
