---
# defaults file for winrm

# WinRM configuration script URL
winrm_config_script_url: "https://raw.githubusercontent.com/ansible/ansible-documentation/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"

# Whether to allow basic authentication
winrm_allow_basic_auth: true

# Whether to allow unencrypted connections
winrm_allow_unencrypted: true

# Temporary directory for downloads
winrm_temp_dir: "C:\\temp"
