---
run_tasks: true
installer_dir: /vagrant/installers
chrome_signing_key_url: https://dl-ssl.google.com/linux/linux_signing_key.pub
chrome_apt_repository: "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] https://dl.google.com/linux/chrome/deb/ stable main"
chrome_driver_version: "2.41"
chrome_driver_server_installer_tar: chromedriver_linux64.zip
chrome_driver_url: https://chromedriver.storage.googleapis.com/
chrome_driver_install_dir: /usr/local/bin
