---
CONFIG_DIR: /etc/asterisk
SOURCE_DIR: /usr/src/asterisk
CUSTOM_SOUNDS_PATH: /var/lib/asterisk/sounds/en/custom
ASTERISK_LOG: /var/log/asterisk
ASTERISK_VERSION: asterisk-20.11.1.tar.gz
ASTERISK_PACKAGE: "https://downloads.asterisk.org/pub/telephony/asterisk/old-releases/{{ ASTERISK_VERSION}}"

## End Override
ASTERISK_GROUP: asterisk
ASTERISK_USER: asterisk
ASTERISK_ASSETS_USER: asterisk_assets
ASTERISK_USER_PASS: asterisk

FAIL2BAN_ASTERISK_PORTS: 5060,5061,5080,8088,8089
FAIL2BAN_ASTERISK_LOG: /var/log/asterisk/security
FAIL2BAN_ASTERISK_MAX_RETRIES: 10
FAIL2BAN_ASTERISK_BAN_TIME: 8h