---
- name: "Block to Allow Loading of Variables without running task"
  when: run_tasks
  block:
    - name: "Creating the Vaultwarden data directory"
      ansible.builtin.file:
        path: "{{ vaultwarden_data_dir }}"
        state: directory
        mode: "0750"

    - name: "Deploying the Vaultwarden container"
      community.docker.docker_container:
        name: "{{ vaultwarden_container_name }}"
        image: "{{ vaultwarden_image }}"
        restart_policy: "{{ vaultwarden_restart_policy }}"
        env: >-
          {{
            {
              'DOMAIN': vaultwarden_domain,
              'ADMIN_TOKEN': vaultwarden_admin_token,
              'SIGNUPS_ALLOWED': vaultwarden_signups_allowed | string | lower,
              'WEBSOCKET_ENABLED': vaultwarden_websocket_enabled | string | lower
            } | combine(vaultwarden_extra_env)
          }}
        volumes:
          - "{{ vaultwarden_data_dir }}:/data"
        published_ports:
          - "{{ vaultwarden_web_port }}:80"
        state: started
