---
- name: Get disk facts
  ansible.windows.win_command: wmic cpu get caption, deviceid, name, numberofcores, maxclockspeed, status
  register: usage

-
  name: Debug
  ansible.builtin.debug:
    msg: "{{ usage.stdout }}"
