---
-
  name: Ensure that Google Chrome Update is Set to manual
  ansible.windows.win_service:
    name: gupdate
    start_mode: manual

-
  name: Ensure that Telegraf is Set to Automatic and Started
  ansible.windows.win_service:
    name: telegraf
    start_mode: delayed
    state: started
