---
# -
#   name: Get App instance version
#   win_file_version:
#     path: 'C:\Program Files (x86)\MyProgram\program.exe'
#   register: exe_file_version

# -
#   name: Debugging App Version
#   ansible.builtin.debug:
#     msg: '{{ exe_file_version.file_version }}'

-
  name: "Set timezone to 'Central Standard Time' (GMT-06:00)"
  ansible.windows.win_timezone:
    timezone: Central Standard Time

-
  name: Get product id and product key
  ansible.windows.win_product_facts:

-
  name: Debug
  ansible.builtin.debug:
    var: hostvars[inventory_hostname]

-
  name: Install package dependencies
  chocolatey.chocolatey.win_chocolatey:
    name:
      - chocolatey-core.extension
      - chocolatey-windowsupdate.extension
    state: present

-
  name: Install all security, critical, and rollup updates without a scheduled task
  ansible.windows.win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
