---
- name: "Block to Allow Loading of Variables without running task"
  when: run_tasks
  block:
    - name: "Installing Required Jenkins Dependencies -- Takes about 5 Mins"
      ansible.builtin.apt:
        name: "{{ packages }}"
      vars:
        packages:
          - gnupg
          - xmlstarlet
          - git-core

    - name: "Creating Backup Directory for Script outputs"
      ansible.builtin.file:
        path: /backup
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "0755"
        state: directory
    - name: "Installing Jenkins Apt Key"
      ansible.builtin.apt_key:
        state: present
        url: "https://pkg.jenkins.io/debian/jenkins.io.key"
    - name: "Creating Jenkins Sources.list folder"
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/jenkins.list
        state: touch
    - name: "Adding Jenkins to Sources.list"

      ansible.builtin.lineinfile:
        line: "deb http://pkg.jenkins.io/debian-stable binary/"
        path: /etc/apt/sources.list.d/jenkins.list
    - name: "Installing Jenkins -- Takes about 3 Minutes"
      ansible.builtin.apt:
        name: "{{ packages }}"
        install_recommends: false
        update_cache: true
      vars:
        packages:
          - jenkins
    - name: "Starting Jenkins Service"
      ansible.builtin.service:
        enabled: false
        name: jenkins
        state: restarted
    - name: "Stopping Jenkins Service"
      ansible.builtin.service:
        enabled: false
        name: jenkins
        state: stopped
    - name: "Preparing Jenkins Cache folder permissions for user setup"
      ansible.builtin.file:
        group: "{{ group }}"
        mode: "0751"
        owner: "{{ user }}"
        path: /var/cache/jenkins
        recurse: true
    - name: "Preparing Jenkins Library folder permissions for user setup"
      ansible.builtin.file:
        group: "{{ group }}"
        owner: "{{ user }}"
        path: /var/lib/jenkins
        recurse: true
    - name: "Preparing Jenkins run folder permissions for user setup"
      ansible.builtin.file:
        group: "{{ group }}"
        owner: "{{ user }}"
        path: /var/run/jenkins
        recurse: true
    - name: "Preparing Jenkins log folder permissions for user setup"
      ansible.builtin.file:
        group: "{{ group }}"
        owner: "{{ user }}"
        path: /var/log/jenkins
        recurse: true
    - name: "Skipping Initial Configuration"

      ansible.builtin.lineinfile:
        regexp: "^JAVA_ARGS="
        line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
        path: /etc/default/jenkins
    - name: "Setting Jenkins to start as user"
      ansible.builtin.lineinfile:
        insertafter: "^# user and group"
        line: JENKINS_USER="{{ user }}"
        path: /etc/default/jenkins
        regexp: ^JENKINS_USER=
    - name: "Setting Jenkins to start as user"
      ansible.builtin.lineinfile:
        insertafter: "^# user and group"
        line: JENKINS_GROUP="{{ group }}"
        path: /etc/default/jenkins
        regexp: ^JENKINS_GROUP=
    - name: "Starting Jenkins Service"
      ansible.builtin.service:
        enabled: false
        name: jenkins
        state: started
    - name: "Waiting for Jenkins Config.XML to generate before stopping service."
      ansible.builtin.pause:
        minutes: 1
    - name: "Stopping Jenkins Service"
      ansible.builtin.service:
        enabled: false
        name: jenkins
        state: stopped
    - name: "Backing up Config.XML to Config.XML.orig"

      ansible.builtin.copy:
        dest: /var/lib/jenkins/config.xml.orig
        src: /var/lib/jenkins/config.xml
        remote_src: true
    - name: "Configuring Jenkins"
      become: true
      ansible.builtin.shell: "cd /var/lib/jenkins && tail -n +2 config.xml.orig >config.xml && xmlstarlet edit --inplace -u '/hudson/useSecurity' -v 'false' config.xml && xmlstarlet edit --inplace -d '/hudson/authorizationStrategy'
        config.xml && xmlstarlet edit --inplace -d '/hudson/securityRealm' config.xml && xmlstarlet edit --inplace -u '/hudson/installStateName' -v 'RUNNING' config.xml &&  diff -u config.xml{.orig,} ||
        true"

    - name: "Checking if /var/lib/jenkins/init.groovy.d exists"
      ansible.builtin.stat:
        path: /var/lib/jenkins/init.groovy.d
      register: output_folder

    - name: "Creating output directory if not exists"
      ansible.builtin.file:
        path: /var/lib/jenkins/init.groovy.d
        state: directory
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "0775"
      when: output_folder.stat.exists == false

    - name: "Disabling the Security Check so we can download Plugins"
      become: true
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "0644"
      with_items:
        - { src: basic-security.groovy.j2, dest: "/var/lib/jenkins/init.groovy.d/basic-security.groovy" }
    - name: "Starting Jenkins Service"
      ansible.builtin.service:
        enabled: true
        name: jenkins
        state: started
    - name: "Downloading  Jenkins CLI from localhost"
      delay: 5
      ansible.builtin.get_url:
        dest: "/home/{{ user }}/jenkins-cli.jar"
        url: "http://localhost:8080/jnlpJars/jenkins-cli.jar"
      register: jenkinscli_source
      retries: 5
      until: "jenkinscli_source is success"
    - name: "Waiting until Jenkins web API is available"
      ansible.builtin.uri:
        url: "http://localhost:8080/cli/"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 600
      delay: 2
    - name: "Adding Xvfb Plugin details"
      ansible.builtin.template:
        src: org.jenkinsci.plugins.xvfb.Xvfb.xml
        dest: /var/lib/jenkins/
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: u=rwX,g=rX,o=rX
    - name: "Installing Jenkins Plugins"
      become: true
      ansible.builtin.shell: "cd /home/{{ user }} && java -jar jenkins-cli.jar -s http://localhost:8080/ install-plugin xvfb xunit workflow-step-api scm-api structs junit script-security git email-ext email-ext-recipients-column
        mailer"
      retries: 5
      delay: 5
    - name: "Configuring git Email"
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ certbot_admin_email }}"
    - name: "Configuring git User Name"
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ jenkins_git_user }}"
    - name: "Configuring git Push"
      community.general.git_config:
        name: push.default
        scope: global
        value: simple
    - name: "Configuring git AutoCRLF"
      community.general.git_config:
        name: core.autocrlf
        scope: global
        value: false
    - name: "Finding Java accessibility.properties files"
      ansible.builtin.find:
        paths: /etc
        patterns: accessibility.properties
        recurse: true
        depth: 2
      register: java_accessibility_files

    - name: "Fixing Java Assistive Tech"
      ansible.builtin.lineinfile:
        insertafter: "^#assistive_technologi"
        line: "#"
        path: "{{ item.path }}"
        regexp: "^assistive_technologi"
      loop: "{{ java_accessibility_files.files }}"
      loop_control:
        label: "{{ item.path }}"
    - name: "Setting {{ user }} permissions"
      ansible.builtin.file:
        group: "{{ group }}"
        owner: "{{ user }}"
        path: "/home/{{ user }}"
        recurse: true
    - name: "Removing Groovy Startup Bypass"
      ansible.builtin.file:
        path: /var/lib/jenkins/init.groovy.d/basic-security.groovy
        state: absent
    - name: "Adding Jenkins Desktop Icon"
      become: true
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "0755"
      with_items:
        - { src: "jenkins.desktop", dest: "/usr/share/applications/jenkins.desktop" }
        - { src: "jenkins.desktop", dest: "/home/{{ user }}/Desktop/jenkins.desktop" }

    - name: "Ensuring that Desktop Icons are Launchable"
      ansible.builtin.command: "dbus-launch gio set {{ item }}  \"metadata::trusted\" true"
      with_items:
        - "/home/{{ user }}/Desktop/jenkins.desktop"
        - "/usr/share/applications/jenkins.desktop"

    - name: "Adding Jenkins Jobs to Desktop"
      become: true
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        remote_src: true
      with_items:
        - { src: /vagrant/jobs, dest: "/home/{{ user }}/Desktop" }
