---
- name: "Block to Allow Loading of Variables without running task"
  when: run_tasks
  block:
    - name: "Checking if Go is Already Installed"
      ansible.builtin.stat:
        path: /usr/local/go/bin/go
      register: go_binary

    - name: "Getting installed Go version"
      ansible.builtin.command: /usr/local/go/bin/go version
      register: go_version_result
      changed_when: false
      when: go_binary.stat.exists

    - name: "Removing Current Go Installation"
      ansible.builtin.file:
        state: absent
        path: /usr/local/go
      when:
        - go_binary.stat.exists
        - go_version not in go_version_result.stdout

    - name: "Downloading Go"
      ansible.builtin.get_url:
        url: "{{ go_download_url }}"
        dest: /usr/local/src/{{ go_tarball }}
        checksum: "sha256:{{ go_checksum }}"
        mode: "0644"
      when: not go_binary.stat.exists or go_version not in go_version_result.stdout

    - name: "Extracting Go"
      ansible.builtin.unarchive:
        src: /usr/local/src/{{ go_tarball }}
        dest: /usr/local
        copy: false
      when: not go_binary.stat.exists or go_version not in go_version_result.stdout

    - name: "Adding Go to System-Wide $PATH"
      ansible.builtin.copy:
        dest: /etc/profile.d/go-path.sh
        mode: "0644"
        content: |-
          export PATH=$PATH:/usr/local/go/bin
