---
-
  name: "Installing keepalived"
  ansible.builtin.apt:
    pkg:
      - keepalived
-
  name: "Configuring keepalived"
  become: true
  tags: keepalived
  ansible.builtin.template:
    owner: "{{ item.owner }}"
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "a+x"
  loop:
    - { src: 'keepalived.conf.j2', dest: '/etc/keepalived/keepalived.conf', owner: 'keepalived' }

-
  name: "Enabling and Starting service keepalived"
  ansible.builtin.service:
    enabled: true
    name: keepalived
    state: restarted
  tags: keepalived
