---
galaxy_info:
  role_name: telegraf
  author: Mark Gilbert
  description: Installs and configures the Telegraf metrics agent on Linux, FreeBSD, macOS, Windows, and Docker.
  company: STARTcloud
  issue_tracker_url: https://github.com/STARTcloud/startcloud_roles/issues
  license: Apache-2.0
  min_ansible_version: '2.15'
  platforms:
    - name: Debian
      versions: ['bookworm', 'trixie']
    - name: Ubuntu
      versions: ['jammy', 'noble']
    - name: EL
      versions: ['8', '9']
    - name: opensuse
      versions: ['15.5']
    - name: FreeBSD
      versions: ['14.0']
    - name: MacOSX
      versions: ['all']
    - name: Windows
      versions: ['2022']
  galaxy_tags:
    - monitoring
    - telegraf
    - metrics
    - influxdb
dependencies: []
collections:
  - startcloud.startcloud_roles
