---
- name: "Restart haproxy"
  ansible.builtin.service:
    name: rh-haproxy18-haproxy
    state: restarted

- name: "Reload haproxy"
  ansible.builtin.service:
    name: rh-haproxy18-haproxy
    state: reloaded
