---
-
  name: "Loggin playbook progress"
  ansible.builtin.debug:
    msg:
      - "Installing fail2ban"
      - "72"

-
  name: "Installing fail2ban"
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: no
  register: result
  retries: 10
  delay: 5
  until: result is success or ('Unable to acquire the dpkg frontend lock' not in result.msg and '/var/lib/dpkg/lock-frontend' not in result.msg)

-
  name: "Creating fail2ban directories if they do not exist"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - "/etc/fail2ban"
    - "/etc/fail2ban/jail.d"

-
  name: "Starting and Enabling fail2ban"
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    enabled: true
