---
galaxy_info:
  role_name: bginfo
  author: Mark Gilbert
  description: Installs and configures Sysinternals BGInfo to display system information on the Windows desktop at startup.
  company: STARTcloud
  issue_tracker_url: https://github.com/STARTcloud/startcloud_roles/issues
  license: Apache-2.0
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions: ["2022"]
  galaxy_tags:
    - windows
    - bginfo
    - background
    - system
dependencies: []
collections:
  - startcloud.startcloud_roles
