---
- name: "Block to Allow Loading of Variables without running task"
  when: run_tasks and (quick_start | default(false))
  block:
    ## This Ansible playbook demonstrates the setup of a Python Simple HTTP server within a virtual environment,
    ## including directory creation, package installation, service configuration, and support bundle generation.
    # It's designed to be easily understood and replicated by team members.
    - name: "Gathering facts on current container"
      community.docker.current_container_facts:

    - name: "Creating Installation Directories" # Creates directories for images and ids under the Python Simple Web Server path.
      ansible.builtin.file:
        path: "{{ item }}" # Specifies the path for each directory.
        state: directory # Ensures the directory exists.
        mode: "0755" # Sets the directory permissions.
        owner: "{{ service_user }}"
        group: "{{ service_group }}"
      with_items: # Directories to be created, interpolated with variables from default/main.yml
        - "{{ python_simple_web_server_path }}/images"
        - "{{ python_simple_web_server_path }}/ids"
        - "{{ python_simple_web_server_path }}/.cache"
        - "{{ python_simple_web_server_path }}/.cache/pip"
        - "{{ python_simple_web_server_path }}/.local"

    - name: "Installing uploadserver for Python Web Server" # Installs the uploadserver package for the Python web server.
      become_user: "{{ service_user }}"
      become: true
      ansible.builtin.pip:
        name: "uploadserver" # Specifies the pip package name.
        extra_args: --user --break-system-packages # Installs the package for the current user and allows breaking system packages if necessary.

    - name: "Installing uploadserver for Python Web Server" # Installs the uploadserver package for the Python web server.
      ansible.builtin.pip:
        name: "uploadserver" # Specifies the pip package name.
        extra_args: --user --break-system-packages # Installs the package for the current user and allows breaking system packages if necessary.

    - name: "Running in-container tasks"
      when: ansible_module_running_in_container
      block:
        - name: "Grabbing External IP address"
          ansible.builtin.shell: |
            ip a | awk '/inet / {print $2}' | cut -d'/' -f1
          args:
            executable: /bin/bash
          register: address

        - name: "Setting Address"
          ansible.builtin.set_fact:
            local_ip: "{{ address.stdout }}"

        - name: "Printing external IP address details"
          ansible.builtin.debug:
            msg:
              - "{{ address }}"

    - name: "Gathering Networking Configurations"
      when:
        - not ansible_module_running_in_container
        - ansible_virtualization_type != "virtualbox"
      become: true
      block:
        - name: "Gathering networking details"
          ansible.builtin.include_tasks: "gather.yml"

        - name: "Storing first adapter details as facts"
          ansible.builtin.set_fact:
            local_ip: "{{ first_adapter_details.ip }}"

    - name: "Configuring Virtualbox networking"
      when:
        - not ansible_module_running_in_container
        - ansible_virtualization_type == "virtualbox"
      become: true
      block:
        - name: "Gathering networking details"
          ansible.builtin.include_tasks: "gather.yml"

        - name: "Storing first adapter details as facts"
          ansible.builtin.set_fact:
            local_ip: "{{ second_adapter_details.ip }}"

    - name: "Placing Python Simple HTTP Server Service file" # Copies service configuration files to their respective locations.
      become: true # Executes the task with elevated privileges.
      ansible.builtin.template:
        owner: "{{ item.owner }}" # Sets the owner of the file.
        src: "{{ item.src }}" # Specifies the source file.
        dest: "{{ item.dest }}" # Specifies the destination file.
        mode: "0644" # Sets the file permissions.
      loop:
        - { src: "pythonserve.service.j2", dest: "/etc/systemd/system/pythonserve.service", owner: "{{ service_user }}" }
        - { src: "environment.j2", dest: "/etc/pythonserv", owner: "{{ service_user }}" }
        - { src: "styles.css", dest: "{{ python_simple_web_server_path }}/styles.css", owner: "{{ service_user }}" }
        - { src: "cockpit.conf.j2", dest: "/etc/cockpit/cockpit.conf", owner: "{{ service_user }}" }

    - name: "Placing Python Simple HTTP Server Service file" # Copies service configuration files to their respective locations.
      become: true # Executes the task with elevated privileges.
      ansible.builtin.template:
        owner: "{{ item.owner }}" # Sets the owner of the file.
        src: "{{ item.src }}" # Specifies the source file.
        dest: "{{ item.dest }}" # Specifies the destination file.
        mode: "0644" # Sets the file permissions.
      loop:
        - { src: "{{ index }}", dest: "{{ python_simple_web_server_path }}/{{ index_name }}", owner: "{{ service_user }}" }

    - name: "Copying Root CA to {{ service_home_dir }}"
      when: selfsigned_enabled and not letsencrypt_enabled
      ansible.builtin.copy:
        mode: "0644"
        src: "{{ item }}"
        dest: "{{ service_home_dir }}"
        remote_src: true
        owner: "{{ service_user }}"
      with_items:
        - "{{ cert_dir }}/ca/ca-certificate.crt"

    - name: "Starting Python Simple HTTP server" # Starts the Python Simple HTTP server service.
      when: not ansible_module_running_in_container
      ansible.builtin.service:
        name: pythonserve # Specifies the service name.
        state: started # Ensures the service is running.
        enabled: true # Enables the service to start on boot.

    - name: "Checking if Python HTTP server is listening on port {{ startcloud_quick_start_port_forwards[0].guest }}" # Checks if Python HTTP server is listening
      when: not ansible_module_running_in_container
      ansible.builtin.wait_for:
        port: "{{ startcloud_quick_start_port_forwards[0].guest }}" # Specifies the port to check.
        delay: 5 # Waits for 5 seconds before checking.
        timeout: 60 # Sets a 60-second timeout for the check.
        msg: "Timeout waiting for {{ startcloud_quick_start_port_forwards[0].guest }} to respond" # Custom message displayed if the check times out.
      register: port_check # Stores the result for later use.
      ignore_errors: true # Ignores errors if the port check fails.

    - name: "Restarting Cockpit" # Restarts the Cockpit service.
      when: not ansible_module_running_in_container
      ansible.builtin.systemd:
        state: restarted # Restarts the service.
        daemon_reload: true # Reloads the systemd manager configuration.
        name: cockpit # Specifies the service name.

    - name: "Copying pythonserver supervisord configuration file"
      when: ansible_module_running_in_container
      ansible.builtin.template:
        src: supervisord.pythonserver.conf.j2
        dest: /etc/supervisor/conf.d/supervisord.pythonserver.conf
        owner: root
        group: root
        mode: "0644"

- name: "Block to always run these tasks"
  when: true
  block:
    - name: "Zipping support bundle"
      community.general.archive:
        mode: "0777"
        path: "/vagrant/support-bundle"
        dest: "{{ python_simple_web_server_path }}/support-bundle.zip"
        format: zip
      ignore_errors: true
