---
-
  name: "Grabbing External IP address"
  ansible.builtin.shell: |
    set -o pipefail
    ip addr show public_adapter | awk '/inet / {print $2}' | cut -d'/' -f1
  args:
    executable: /bin/bash
  register: netoutput
  changed_when: false

-
  name: "Generating Help File"
  become: true
  ansible.builtin.template:
    mode: '0644'
    dest: /tmp/cloud.txt
    src: cloud.txt.j2

-
  name: "Registering Output of available Commands"
  ansible.builtin.command: cat /tmp/cloud.txt
  register: cloud_commands
  changed_when: false

-
  name: "Outputting available Help Text"
  ansible.builtin.debug:
    var: cloud_commands.stdout_lines
