---
-
  name: "Disabling NFS, Exim and Cockpit, reboot to fully apply"
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ lockdown }}"

#-
#  name: "Disabling Default Startcloud SSH Key"
#  ansible.builtin.lineinfile:
#    path: /home/startcloud/.ssh/authorized_keys
#    state: absent
#    regexp: '^%vagrantup'
#
#-
#  name: "Place New SSH Key"
#  ansible.builtin.template:
#    src: id_rsa.j2.pub
#    dest: '/home/startcloud/.ssh/authorized_keys'
