---
-
  name: "Disabling NFS, Exim and Cockpit, reboot to fully apply"
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ lockdown }}"

- 
  name: "Changing startcloud Password"
  user:
    name: "startcloud"
    state: present
    password: "{{ settings.vagrant_user_pass | password_hash('sha512') }}"

- 
  name: "Generating an OpenSSH keypair with the default values"
  community.crypto.openssh_keypair:
    owner: startcloud
    group: startcloud
    path: /home/startcloud/.ssh/id_ssh_rsa

- 
  name: "Appending SSH public key to authorized_keys"
  ansible.builtin.lineinfile:
    path: /home/startcloud/.ssh/authorized_keys
    insertafter: EOF
    line: "{{ lookup('file', '/home/startcloud/.ssh/id_ssh_rsa.pub') }}"

-
  name: "Disabling Default Startcloud SSH Key"
  ansible.builtin.lineinfile:
    path: /home/startcloud/.ssh/authorized_keys
    state: absent
    regexp: '^%vagrantup'
