---
- 
  name: "Send back VM completion request to Docova.com"
  register: status
  uri: 
    body: "action=spinupupdate&token={{ token }}&instanceurl={{id}}&trackerid={{ trackerid }}&iscomplete=yes"
    headers: 
      Content-Type: application/x-www-form-urlencoded
    method: POST
    status_code: 200
    url: "https://docova.com/wp-admin/admin-ajax.php"
