---
- name: "Starting HADR as primary on: {{ db2dbname }}"
  ansible.builtin.command: "su - {{ db2usr }} -c 'db2 start hadr on database {{ db2dbname }} as primary'"
  changed_when: true

- name: "Running the HADR Monitoring Tool"
  ansible.builtin.command: "su - {{ db2usr }} -c 'db2pd -alldbs -hadr'"
  changed_when: false
