---
-
    name: "Installing required dependencies"
    ansible.builtin.apt:
        name:
            - apt-transport-https
            - gnupg2
        state: present

-
    name: "Adding Elasticsearch APT key"
    ansible.builtin.apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

-
    name: "Adding Elasticsearch repository"
    ansible.builtin.apt_repository:
        repo: 'deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main'
        state: present
        update_cache: true
