---
-
  name: "Downloading MongoDB GPG Key"
  ansible.builtin.get_url:
    url: "https://pgp.mongodb.com/server-{{ graylog_mongodb_version }}.asc"
    dest: "/usr/share/keyrings/mongodb-server-{{ graylog_mongodb_version }}.asc"
    mode: '0644'

-
  name: "Adding MongoDB APT Repository"
  ansible.builtin.apt_repository:
    repo: "deb [ signed-by=/usr/share/keyrings/mongodb-server-{{ graylog_mongodb_version }}.asc ] https://repo.mongodb.org/apt/{{ ansible_distribution | lower }} {{ ansible_distribution_release }}/mongodb-org/{{ graylog_mongodb_version }} {{ 'main' if ansible_distribution == 'Debian' else 'multiverse' }}"
    filename: "mongodb-org-{{ graylog_mongodb_version }}"
    state: present

-
  name: "Installing MongoDB Server"
  ansible.builtin.apt:
    name: mongodb-org
    state: present
    update_cache: true

-
  name: "Rendering MongoDB Configuration"
  ansible.builtin.template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restarting MongoDB

-
  name: "Enabling and Starting MongoDB"
  ansible.builtin.systemd:
    name: mongod
    enabled: true
    state: started
    daemon_reload: true
