---
mongodb_apt_key_url: "https://www.mongodb.org/static/pgp/server-{{ mongodb_major_version }}.asc"
mongodb_apt_key_armored_path: "/etc/apt/keyrings/mongodb-server-{{ mongodb_major_version }}.asc"
mongodb_apt_keyring_path: "/etc/apt/keyrings/mongodb-server-{{ mongodb_major_version }}.gpg"
mongodb_repository: >-
  deb [arch={{ mongodb_deb_architecture.stdout }} signed-by={{ mongodb_apt_keyring_path }}]
  https://repo.mongodb.org/apt/debian
  {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_major_version }} main

mongodb_pymongo_package: python3-pymongo
mongodb_pymongo_deps:
  - python3-dev
  - python3-pip
mongodb_python_setuptools: python3-setuptools
mongodb_pip_executable: pip3
