---
mongodb_repository: "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongodb_major_version }}/$basearch/"
mongodb_repository_gpgkey: "https://www.mongodb.org/static/pgp/server-{{ mongodb_major_version }}.asc"

mongodb_pidfile_path: "{{ '/var/run/mongodb/mongod.pid' if ('mongodb-org' in mongodb_package) else '' }}"

yum_lock_timeout: 180

mongodb_pymongo_package: python3-pymongo
mongodb_pymongo_deps:
  - python3-devel
  - python3-pip
mongodb_pip_executable: pip3
