---
run_tasks: true

uds_actor_version: 3.6.0
uds_actor_managed: false
uds_actor_installer: "UDSActorSetup-{{ uds_actor_version }}.exe"
installer_file:
  app: UDS-Actor
  version: "{{ uds_actor_version }}"
  variant: release
  name: "{{ uds_actor_installer }}"
uds_installer_url: "{{ installer_url }}"
