---
-
  name: "Installing NFS client utilities"
  become: true
  ansible.builtin.package:
    name: nfs-utils
    state: present

-
  name: "Ensuring rpcbind is running"
  become: true
  ansible.builtin.service:
    name: rpcbind
    state: started
    enabled: true
