---
-
  name: "Including OS-specific vars"
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

-
  name: "Create pkg proxy configuration: /usr/local/etc/pkg/repos/proxy.conf"
  ansible.builtin.template:
    src: pkg_proxy.conf.j2
    dest: /usr/local/etc/pkg/repos/proxy.conf
    mode: '0644'
  when: use_proxy | bool

-
  name: "Self-upgrade pkg before installing other packages (pkg mid-install self-upgrades can abort subsequent work)"
  community.general.pkgng:
    name: pkg
    state: latest

-
  name: "Installing baseline packages"
  community.general.pkgng:
    name: "{{ packages }}"
    state: present

-
  name: "Installing extra packages"
  community.general.pkgng:
    name: "{{ extra_packages }}"
    state: present
  when: extra_packages | default([]) | length > 0
