---
- name: "Converge"
  hosts: all
  become: true
  vars:
    run_tasks: true
    openfortivpn_packages:
      - openfortivpn
    openfortivpn_enable_service: false
    openfortivpn_host: "vpn.startcloud.test"
    openfortivpn_port: 10443
    openfortivpn_user: "startcloud"
    openfortivpn_password: "CHANGEME"
    openfortivpn_trusted_cert: "de6f2b1a1d4f6f9a0c5b7e8d3a2c1b0f9e8d7c6b5a4938271605f4e3d2c1b0a9"
  tasks:
    - name: "Including the openfortivpn_client role"
      ansible.builtin.include_role:
        name: openfortivpn_client
