---
- name: "Converge"
  hosts: all
  become: true
  vars:
    run_tasks: true
    prometheus_version: "2.53.1"
    prometheus_user: prometheus
    prometheus_group: prometheus
    prometheus_install_dir: /usr/local/bin
    prometheus_config_dir: /etc/prometheus
    prometheus_data_dir: /var/lib/prometheus
    prometheus_listen_address: "0.0.0.0:9090"
    prometheus_storage_retention: "15d"
    prometheus_scrape_interval: "15s"
    prometheus_evaluation_interval: "15s"
  roles:
    - role: prometheus
