---
# defaults file for windows_ssh

# SSH key source path (relative to ansible directory)
ssh_key_source: "../../../../../../ansible/ssh_keys/id_rsa.pub"

# SSH configuration
ssh_default_shell: "C:\\tools\\cygwin\\bin\\bash.exe"
ssh_default_shell_option: "-c"

# Uptime utility files
uptime_files:
  - "C:\\Windows\\system32\\uptime.exe"
  - "C:\\Windows\\system32\\uptime"
  - "C:\\tools\\cygwin\\bin\\uptime.exe"
  - "C:\\tools\\cygwin\\bin\\uptime"
