---
- name: "Gathering Disks"
  become: true
  ansible.builtin.shell: "pfexec ls /dev/dsk/"
  args:
    executable: /usr/bin/ksh
  register: dir_out
  changed_when: false

- name: "Setting rpool to autoexpand"
  become: true
  ansible.builtin.command: pfexec zpool set autoexpand=on rpool
  changed_when: true

- name: "Gathering rpool disk list"
  become: true
  register: result_rpool_disk_list
  ansible.builtin.shell: |
    set -o pipefail
    pfexec zpool status rpool | grep ONLINE | egrep -v "rpool|state" | awk '{print $1}'
  args:
    executable: /usr/bin/ksh
  changed_when: false

- name: "Checking if the zpool exists"
  become: true
  ansible.builtin.command: "zpool list -Ho name {{ zfs_pool_name }}"
  register: result_pool_list
  failed_when: result_pool_list.rc not in [0, 1]
  changed_when: false

- name: "Creating ZFS pool"
  become: true
  ansible.builtin.command: >-
    pfexec zpool create
    {{ '-o' if zpool_options else '' }} {{ zpool_options | join(' -o ') }}
    {{ '-O' if zfs_pool_options else '' }} {{ zfs_pool_options | join(' -O ') }}
    {{ '-m ' + zfs_pool_mountpoint if zfs_pool_mountpoint else '' }}
    {{ zfs_pool_name }}
    {{ zfs_pool_mode if zfs_pool_mode else '' }}
    {{ zfs_pool_devices | join(' ') }}
  changed_when: true
  when:
    - zfs_pool_state | default('present') == 'present'
    - result_pool_list.rc == 1

- name: "Destroying ZFS pool"
  ansible.builtin.command: zpool destroy {{ zfs_pool_name }}
  changed_when: true
  when:
    - zfs_pool_state | default('present') == 'absent'
    - result_pool_list.rc == 0

- name: "Expanding rpool"
  become: true
  args:
    executable: /usr/bin/ksh
  ansible.builtin.shell: "pfexec zpool online -e rpool {{ result_rpool_disk_list.stdout }}"
  changed_when: true
