---
galaxy_info:
  role_name: cleanup
  author: MarkProminic
  description: Cleanup Images for Packer
  company: STARTCloud
  issue_tracker_url: https://github.com/STARTcloud/startcloud_roles/issues
  license: license (Apache)
  min_ansible_version: '2.9'
  platforms:
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags: []

dependencies: []

collections:
  - startcloud.startcloud_roles

allow_duplicates: false
