---
-
  name: "Reloading systemd Daemon"
  ansible.builtin.systemd_service:
    daemon_reload: true

-
  name: "Restarting openfortivpn"
  ansible.builtin.systemd_service:
    name: "openfortivpn.service"
    state: restarted
  when: openfortivpn_enable_service
